<a href="https://colab.research.google.com/github/lokeshwarinayak/intenship/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

** Series** :A Pandas Series is a one-dimensional array of indexed data.

In [4]:
import numpy as np
import pandas as pd

data=pd.Series([0.25,1])
data


0    0.25
1    1.00
dtype: float64

In [5]:
data=pd.Series([1,7,9])
data


0    1
1    7
2    9
dtype: int64

**values**:-
The values are simply a familiar NumPy array


In [6]:
data.values

array([1, 7, 9])

In [7]:
data.index

RangeIndex(start=0, stop=3, step=1)

In [8]:
data[2]

9

In [9]:
data[1:3]

1    7
2    9
dtype: int64

Series as generalized NumPy array

In [11]:
data = pd.Series([0.25, 0.5, 0.75, 1.0, 0.83, 1.1],
                 index=['n', 'i', 't', 'h' ,'y' ,'a'])
data

n    0.25
i    0.50
t    0.75
h    1.00
y    0.83
a    1.10
dtype: float64

In [12]:
data['t']

0.75

In [13]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

Series as specialized dictionary

In [14]:
priends_dict = {'nithya': 38332521,
                   'mrudu': 26448193,
                   'chaithra': 19651127,
                   'pavi': 19552860,
                   'divya': 12882135}
priends = pd.Series(priends_dict)
priends

nithya      38332521
mrudu       26448193
chaithra    19651127
pavi        19552860
divya       12882135
dtype: int64

In [16]:
priends['nithya']

38332521

In [17]:
priends['nithya':'pavi']

nithya      38332521
mrudu       26448193
chaithra    19651127
pavi        19552860
dtype: int64

Constructing Series objects

scalar data repeatedly filling in specified index

In [19]:
data=pd.Series(5,index=[1,3,5])
data


1    5
3    5
5    5
dtype: int64

storing data as dictionary
data can be a dictionary, in which index defaults to the sorted dictionary keys

In [23]:
data=pd.Series({2:'4',1:'3',3:'1'})
data

2    4
1    3
3    1
dtype: object

In [26]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3])

3    c
dtype: object

DataFrame as a generalized NumPy array¶

In [27]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [29]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [30]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [31]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [32]:
states.columns

Index(['population', 'area'], dtype='object')

DataFrame as specialized dictionary

In [33]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

**Constructing DataFrame objects**

In [34]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

From a list of dicts

In [36]:
data = [{'a': i, 'b': 2 * i}
        for i in range(9)]
pd.DataFrame(data)

a   b
0  0   0
1  1   2
2  2   4
3  3   6
4  4   8
5  5  10
6  6  12
7  7  14
8  8  16

In [39]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4},{}])

a    b    c
0  1.0  2.0  NaN
1  NaN  3.0  4.0
2  NaN  NaN  NaN

From a dictionary of Series objects

In [40]:
pd.DataFrame({'population': population,
              'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

From a two-dimensional NumPy array

In [45]:
pd.DataFrame(np.random.rand(4, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c','d'])

foo       bar
a  0.030614  0.572074
b  0.490234  0.049725
c  0.892548  0.843765
d  0.836429  0.468752

From a NumPy structured array

In [46]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [47]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

The Pandas Index Object

In [48]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

Index as immutable array

In [52]:
ind[1]


3

In [53]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

Index objects also have many of the attributes familiar from NumPy arrays:

In [54]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


Index as ordered set

In [56]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

indA & indB 

Int64Index([3, 5, 7], dtype='int64')

In [57]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [58]:
indA ^ indB 

Int64Index([1, 2, 9, 11], dtype='int64')

Data Selection in Series
Series as dictionary

In [59]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [61]:
data['a']

0.25

In [62]:


list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [65]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [63]:
'a' in data

True

Series as one-dimensional array

In [66]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [67]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [68]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [69]:
# fancy indexing
data[['a', 'e']]

/usr/local/lib/python3.6/dist-packages/pandas/core/series.py:951: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]


a    0.25
e     NaN
dtype: float64

Indexers: loc, iloc, and ix


 The loc attribute allows indexing and slicing that always references the explicit index

In [71]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data


1    a
3    b
5    c
dtype: object

In [83]:
data.loc[5]

'c'

In [73]:
data.loc[1:3]

1    a
3    b
dtype: object

The iloc attribute allows indexing and slicing that always references the implicit index

In [84]:
data.iloc[3]

IndexError: ignored

In [85]:
data.iloc[1:3]

3    b
5    c
dtype: object

Data Selection in DataFrame

DataFrame as a dictionary

In [86]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [87]:
data.area #data['area']


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [88]:
data.area is data['area']

True

In [89]:
data.pop

<bound method NDFrame.pop of               area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135>

In [91]:
data['pop']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

In [90]:
data.pop is data['pop']

False

In [92]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

DataFrame as two-dimensional array

In [95]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [96]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [97]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [98]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [99]:

data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [100]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

Additional indexing conventions

In [101]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [102]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [103]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

Ufuncs: Index Preservation¶


In [104]:
import pandas as pd
import numpy as np
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 20, 4))
ser

0     6
1    19
2    14
3    10
dtype: int64

In [105]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  7  4  6  9
1  2  6  7  4
2  3  7  7  2

In [106]:
np.exp(ser)

0    4.034288e+02
1    1.784823e+08
2    1.202604e+06
3    2.202647e+04
dtype: float64

In [107]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -0.707107  1.224647e-16 -1.000000  7.071068e-01
1  1.000000 -1.000000e+00 -0.707107  1.224647e-16
2  0.707107 -7.071068e-01 -0.707107  1.000000e+00

UFuncs: Index Alignment

Index alignment in Series

In [108]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [109]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [110]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

A.add(B) is equivalent to calling A + B, but allows optional explicit specification of the fill value for any elements in A or B that might be missing

In [111]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

Index alignment in DataFrame

In [113]:
A = pd.DataFrame(rng.randint(0, 10, (2, 2)),
                 columns=list('AB'))
A

A  B
0  4  0
1  9  5

In [114]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  8  0  9
1  2  6  3
2  8  2  4

In [115]:
A + B


A    B   C
0   4.0  8.0 NaN
1  15.0  7.0 NaN
2   NaN  NaN NaN

In [116]:
fill = A.stack().mean()
A.add(B, fill_value=fill)


A     B     C
0   4.0   8.0  13.5
1  15.0   7.0   7.5
2   6.5  12.5   8.5

Ufuncs: Operations Between DataFrame and Series

In [117]:
A = rng.randint(10, size=(3, 4))
A

array([[2, 6, 4, 8],
       [6, 1, 3, 8],
       [1, 9, 8, 9]])

In [118]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 4, -5, -1,  0],
       [-1,  3,  4,  1]])

In [119]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  4 -5 -1  0
2 -1  3  4  1

In [120]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -4  0 -2  2
1  5  0  2  7
2 -8  0 -1  0

In [121]:
halfrow = df.iloc[0, ::2]
halfrow

Q    2
S    4
Name: 0, dtype: int64

In [122]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  4.0 NaN -1.0 NaN
2 -1.0 NaN  4.0 NaN

Handling Missing Data

In [123]:
import numpy as np
import pandas as pd
vals1 = np.array([1, None, 3, 4])
vals1


array([1, None, 3, 4], dtype=object)

In [134]:
pop = pd.read_csv('state-population.csv')
areas = pd.read_csv('state-areas.csv')
abbrevs = pd.read_csv('state-abbrevs.csv')



display('pop.head()', 'areas.head()', 'abbrevs.head()')

pop.head()

FileNotFoundError: ignored

In [136]:
pop = pd.read_csv('ba1.csv')
display('pop.head()')
pop.head()
 

'pop.head()'

name  usn adresss    phno
0  acd  900     tmk  244518

In [133]:
pop = pd.read_csv('b1.csv')
display('pop.head()')
pop.head()
 

FileNotFoundError: ignored